### ISSUE TITLE
Please add a screen shot and a license file

### ISSUE THREAD

**Issue by unixorn** [omkarpai/watermelon-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by omkarpai** [comment]
Sure thing. I've added screenshots for the theme as well as my terminal profile setup.

Also thank you for bringing the license file to my notice. [https://choosealicense.com/](https://choosealicense.com/) was really helpful.

Cheers!
